site_name: SC-machine

extra_css:
  - _assets/main.css
  
extra_javascript:
  - _assets/scg.min.js
  - _assets/main.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
  - Home: index.md
  - Build:
    - Build on Linux: build/linux-build.md
    - Build on Windows: build/windows-build.md
    - Build on OSX: build/osx-build.md
  - Development:
    - Git-workflow: dev/git-workflow.md
    - Pull requets: dev/pr.md
    - Codestyle: dev/codestyle.md
  - Common:
    - Element types: cpp/el_types.md
    - Configuration files: other/config.md
    - SCs language: other/scs.md
  - API:
    - Meta programming: cpp/cpp-meta.md
    - Agents: cpp/kpm.md
    - Template: cpp/templates.md
    - Common: cpp/common.md
  - Network:
      - Common: net/index.md
      - Sctp: net/sctp.md
  - Tools:
      - Builder: tools/kb_builder.md
      - Server: tools/sc-server.md
      - Web: tools/web.md
  - License: license.md
  - Changelog: changelog.md
  - Thirdparty: thirdparty.md

theme: material

markdown_extensions:
  - markdown_include.include
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences:
    # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
    - search
    - mermaid2